version: '4.30.0'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:16.3
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  nginx:
    build: ./nginx/
    env_file: .env
    ports:
      - "8000:80"
    volumes:
      - static:/staticfiles/
      - media:/app/media/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
  backend:
    build: ./backend/
    env_file: .env
    volumes: 
      - static:/backend_static
      - media:/app/media/
    depends_on:
      - db
