# Generated by Django 5.0.2 on 2024-10-05 11:31

import content.models
import content.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("audiobook", "Аудиокнига"),
                            ("lullaby", "Колыбельная"),
                            ("fairytale", "Сказка"),
                            ("song", "Песня"),
                            ("meditation", "Медитация"),
                        ],
                        max_length=100,
                        verbose_name="Тип контента",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="Название"),
                ),
                (
                    "author",
                    models.CharField(
                        max_length=150, verbose_name="Автор произведения"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        max_length=500, unique=True, verbose_name="Описание"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("newborn", "Самые маленькие (0-3)"),
                            ("babies", "Малыши (3-6)"),
                            ("pupils", "Школьники (7-10)"),
                        ],
                        max_length=150,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "chapter",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Глава"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        choices=[
                            ("morning", "Утро"),
                            ("noon", "День"),
                            ("evening", "Вечер"),
                        ],
                        max_length=150,
                        verbose_name="Тег",
                    ),
                ),
                (
                    "pub_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=content.models.set_path_name,
                        validators=[content.validators.validate_file_type],
                        verbose_name="Файл",
                    ),
                ),
                (
                    "duration",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Продолжительность"
                    ),
                ),
                (
                    "is_free",
                    models.BooleanField(verbose_name="Бесплатный контент"),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="content",
            constraint=models.UniqueConstraint(
                fields=("title", "author"),
                name="unique_fairytale_title_author",
            ),
        ),
    ]
