# Generated by Django 5.0.2 on 2024-06-04 20:31

import content.models
import content.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AudioBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Название")),
                (
                    "pub_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата загрузки"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=content.models.set_path_name,
                        validators=[content.validators.validate_file_type],
                        verbose_name="Файл",
                    ),
                ),
                (
                    "duration",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Продолжительность"
                    ),
                ),
                ("is_free", models.BooleanField(verbose_name="Бесплатный контент")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, unique=True, verbose_name="Описание"
                    ),
                ),
                ("author", models.CharField(max_length=150, verbose_name="Автор")),
                (
                    "chapter",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Глава"
                    ),
                ),
            ],
            options={
                "verbose_name": "Аудио книга",
                "verbose_name_plural": "Аудиокниги",
                "ordering": ["-pub_date"],
            },
        ),
        migrations.CreateModel(
            name="Fairytale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Название")),
                (
                    "pub_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата загрузки"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=content.models.set_path_name,
                        validators=[content.validators.validate_file_type],
                        verbose_name="Файл",
                    ),
                ),
                (
                    "duration",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Продолжительность"
                    ),
                ),
                ("is_free", models.BooleanField(verbose_name="Бесплатный контент")),
                (
                    "author",
                    models.CharField(max_length=150, verbose_name="Автор произведения"),
                ),
                (
                    "description",
                    models.TextField(
                        max_length=500, unique=True, verbose_name="Описание"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("newborn", "Самые маленькие (0-3)"),
                            ("babies", "Малыши (3-6)"),
                            ("pupils", "Школьники (7-10)"),
                        ],
                        max_length=150,
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сказка",
                "verbose_name_plural": "Сказки",
                "ordering": ["-pub_date"],
            },
        ),
        migrations.CreateModel(
            name="Lullaby",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Название")),
                (
                    "pub_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата загрузки"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=content.models.set_path_name,
                        validators=[content.validators.validate_file_type],
                        verbose_name="Файл",
                    ),
                ),
                (
                    "duration",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Продолжительность"
                    ),
                ),
                ("is_free", models.BooleanField(verbose_name="Бесплатный контент")),
                (
                    "author",
                    models.CharField(max_length=150, verbose_name="Исполнитель"),
                ),
            ],
            options={
                "verbose_name": "Колыбельная",
                "verbose_name_plural": "Колыбельные",
                "ordering": ["-pub_date"],
            },
        ),
        migrations.CreateModel(
            name="Meditation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="Название")),
                (
                    "pub_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата загрузки"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=content.models.set_path_name,
                        validators=[content.validators.validate_file_type],
                        verbose_name="Файл",
                    ),
                ),
                (
                    "duration",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Продолжительность"
                    ),
                ),
                ("is_free", models.BooleanField(verbose_name="Бесплатный контент")),
                (
                    "category",
                    models.CharField(max_length=150, verbose_name="Категория"),
                ),
                (
                    "tags",
                    models.CharField(
                        choices=[
                            ("morning", "Утро"),
                            ("noon", "День"),
                            ("evening", "Вечер"),
                        ],
                        max_length=150,
                        verbose_name="Тег",
                    ),
                ),
            ],
            options={
                "verbose_name": "Медитация",
                "verbose_name_plural": "Медитации",
                "ordering": ["-pub_date"],
            },
        ),
        migrations.AddConstraint(
            model_name="audiobook",
            constraint=models.UniqueConstraint(
                fields=("title", "chapter"), name="unique_audiobook_title_chapter"
            ),
        ),
        migrations.AddConstraint(
            model_name="fairytale",
            constraint=models.UniqueConstraint(
                fields=("title", "author"), name="unique_fairytale_title_author"
            ),
        ),
        migrations.AddConstraint(
            model_name="lullaby",
            constraint=models.UniqueConstraint(
                fields=("title", "author"), name="unique_lullaby_title_author"
            ),
        ),
    ]
