# Generated by Django 5.0.2 on 2024-10-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="tags",
            field=models.CharField(
                blank=True,
                choices=[
                    ("morning", "Утро"),
                    ("noon", "День"),
                    ("evening", "Вечер"),
                ],
                max_length=150,
                null=True,
                verbose_name="Тег",
            ),
        ),
    ]
