# Generated by Django 5.0.2 on 2024-02-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiobook",
            name="duration",
            field=models.DurationField(
                blank=True, null=True, verbose_name="Продолжительность"
            ),
        ),
        migrations.AlterField(
            model_name="fairytale",
            name="duration",
            field=models.DurationField(
                blank=True, null=True, verbose_name="Продолжительность"
            ),
        ),
        migrations.AlterField(
            model_name="lullaby",
            name="duration",
            field=models.DurationField(
                blank=True, null=True, verbose_name="Продолжительность"
            ),
        ),
        migrations.AlterField(
            model_name="meditation",
            name="duration",
            field=models.DurationField(
                blank=True, null=True, verbose_name="Продолжительность"
            ),
        ),
    ]
