# Generated by Django 5.0.2 on 2024-10-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_alter_content_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="content",
            options={"ordering": ["-pub_date"]},
        ),
        migrations.AlterField(
            model_name="content",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("newborn", "Самые маленькие (0-3)"),
                    ("babies", "Малыши (3-6)"),
                    ("pupils", "Школьники (7-10)"),
                ],
                max_length=150,
                null=True,
                verbose_name="Категория",
            ),
        ),
    ]
