# Generated by Django 5.0.2 on 2024-02-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_alter_meditation_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fairytale",
            name="duration",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Продолжительность"
            ),
        ),
    ]
