# Generated by Django 5.0.2 on 2024-10-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_alter_content_options_alter_content_category"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="content",
            name="unique_fairytale_title_author",
        ),
        migrations.AddConstraint(
            model_name="content",
            constraint=models.UniqueConstraint(
                fields=("title", "author", "chapter"),
                name="unique_fairytale_title_author_chapter",
            ),
        ),
    ]
