# Generated by Django 5.0.2 on 2024-10-19 11:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0004_remove_content_unique_fairytale_title_author_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="content",
            options={
                "ordering": ["-pub_date"],
                "verbose_name": "Контент",
                "verbose_name_plural": "Контент",
            },
        ),
    ]
