# Generated by Django 5.0.2 on 2024-02-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0004_alter_fairytale_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiobook",
            name="duration",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Продолжительность"
            ),
        ),
        migrations.AlterField(
            model_name="audiobook",
            name="file",
            field=models.FileField(
                upload_to="media/audio_files/Fairy tales/", verbose_name="Файл"
            ),
        ),
        migrations.AlterField(
            model_name="audiobook",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата загрузки"
            ),
        ),
        migrations.AlterField(
            model_name="lullaby",
            name="duration",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Продолжительность"
            ),
        ),
        migrations.AlterField(
            model_name="lullaby",
            name="file",
            field=models.FileField(
                upload_to="media/audio_files/Fairy tales/", verbose_name="Файл"
            ),
        ),
        migrations.AlterField(
            model_name="meditation",
            name="file",
            field=models.FileField(
                upload_to="media/audio_files/Fairy tales/", verbose_name="Файл"
            ),
        ),
        migrations.AlterField(
            model_name="meditation",
            name="title",
            field=models.CharField(max_length=150, verbose_name="Название"),
        ),
    ]
