# Generated by Django 5.0.2 on 2024-02-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "content",
            "0005_alter_audiobook_duration_alter_audiobook_file_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiobook",
            name="file",
            field=models.FileField(
                upload_to="audio_files/None", verbose_name="Файл"
            ),
        ),
        migrations.AlterField(
            model_name="fairytale",
            name="file",
            field=models.FileField(
                upload_to="audio_files/None", verbose_name="Файл"
            ),
        ),
        migrations.AlterField(
            model_name="lullaby",
            name="file",
            field=models.FileField(
                upload_to="audio_files/None", verbose_name="Файл"
            ),
        ),
        migrations.AlterField(
            model_name="meditation",
            name="file",
            field=models.FileField(
                upload_to="audio_files/None", verbose_name="Файл"
            ),
        ),
    ]
