# Generated by Django 5.0.2 on 2024-02-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0009_alter_audiobook_file_alter_fairytale_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiobook",
            name="chapter",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Глава"
            ),
        ),
    ]
