# Generated by Django 5.0.2 on 2024-02-11 18:50

import content.models
import content.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0010_alter_audiobook_chapter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audiobook",
            name="file",
            field=models.FileField(
                upload_to=content.models.set_path_name,
                validators=[content.validators.validate_file_type],
                verbose_name="Файл",
            ),
        ),
        migrations.AlterField(
            model_name="fairytale",
            name="file",
            field=models.FileField(
                upload_to=content.models.set_path_name,
                validators=[content.validators.validate_file_type],
                verbose_name="Файл",
            ),
        ),
        migrations.AlterField(
            model_name="lullaby",
            name="file",
            field=models.FileField(
                upload_to=content.models.set_path_name,
                validators=[content.validators.validate_file_type],
                verbose_name="Файл",
            ),
        ),
        migrations.AlterField(
            model_name="meditation",
            name="file",
            field=models.FileField(
                upload_to=content.models.set_path_name,
                validators=[content.validators.validate_file_type],
                verbose_name="Файл",
            ),
        ),
    ]
