# Generated by Django 5.0.2 on 2024-02-17 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0011_alter_audiobook_file_alter_fairytale_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audiobooks",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_audiobook",
                        to="content.audiobook",
                    ),
                ),
                (
                    "fairytales",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_fairytale",
                        to="content.fairytale",
                    ),
                ),
                (
                    "lullabies",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_lullabies",
                        to="content.lullaby",
                    ),
                ),
                (
                    "meditations",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="new_meditation",
                        to="content.meditation",
                    ),
                ),
            ],
        ),
    ]
