# Generated by Django 5.0.2 on 2024-02-17 13:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0012_news"),
    ]

    operations = [
        migrations.DeleteModel(
            name="News",
        ),
    ]
