# Generated by Django 5.0.2 on 2024-02-09 23:50

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_customuser_user_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_pic",
            field=models.ImageField(
                blank=True, null=True, upload_to=users.models.set_user_pic_path
            ),
        ),
    ]
