# Generated by Django 5.0.2 on 2024-02-10 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0009_alter_audiobook_file_alter_fairytale_file_and_more"),
        ("users", "0004_alter_customuser_user_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorite",
            name="audiobooks",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="favorite_audiobooks",
                to="content.audiobook",
                verbose_name="Избранные аудиокниги",
            ),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="fairytales",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="favorite_fairytales",
                to="content.fairytale",
                verbose_name="Избранные сказки",
            ),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="lullabies",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="favorite_lullabies",
                to="content.lullaby",
                verbose_name="Избранные колыбельные",
            ),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="meditations",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="favorite_meditations",
                to="content.meditation",
                verbose_name="Избранные медитации",
            ),
        ),
    ]
